version: "3"
services:
    #PHP Service
    app:
        # build:
        #   context: .
        #   dockerfile: Dockerfile
        image: muhrezaaldiirawan007/larabase:latest
        container_name: lara-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./deploy-ext/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: lara-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./deploy-ext/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - app

    node:
        image: node:latest
        container_name: laravel_node-app
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
        working_dir: /var/www
        command: sh -c "npm install && npm run build"
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:8
        container_name: app-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
        volumes:
            - dbdata:/var/lib/mysql/
            - ./deploy-ext/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
